### ISSUE TITLE
Типы не найдены

### ISSUE THREAD

**Issue by 130120013** [130120013/BMPGenerator#3]
//описание
Компилятор g++ выдает множественные ошибки типа:
error 'uint8_t' in namespace 'std' does not name a type

Возможно, нужно изменить #include <cstdint> на #include <stdint.h>

//(опционально) операционная система 
RHEL 9

**Comment by lpsztemp** [comment]
g++ v 7.3.0: компилируется. 
Подготовь Makefile.
glibc-dev установлено в системе? Это стандартная библиотека C/C++ для gcc, в Red Hat, может, собрать придется - не знаю.
