### ISSUE TITLE
Linux: проблемы с future и async 

### ISSUE THREAD

**Issue by 130120013** [130120013/BMPGenerator#5]
//описание
После исполнения основного сценария Makefile возникают ошибки:
g++ Client.cpp BMPGenerator.cpp -o BMPGenerator -std=c++14
/tmp/ccI4iQaq.o: In function `std::thread::thread<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<double (*)(double*, double*), double*, double*> >, double>::_Async_state_impl(std::thread::_Invoker<std::tuple<double (*)(double*, double*), double*, double*> >&&)::{lambda()#1}>(std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<double (*)(double*, double*), double*, double*> >, double>::_Async_state_impl(std::thread::_Invoker<std::tuple<double (*)(double*, double*), double*, double*> >&&)::{lambda()#1}&&)':
Client.cpp:(.text._ZNSt6threadC2IZNSt13__future_base17_Async_state_implINS_8_InvokerISt5tupleIJPFdPdS5_ES5_S5_EEEEdEC4EOS9_EUlvE_JEEEOT_DpOT0_[_ZNSt6threadC5IZNSt13__future_base17_Async_state_implINS_8_InvokerISt5tupleIJPFdPdS5_ES5_S5_EEEEdEC4EOS9_EUlvE_JEEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'
/tmp/ccI4iQaq.o: In function `std::thread::thread<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<double (*)(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >), __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > >, double>::_Async_state_impl(std::thread::_Invoker<std::tuple<double (*)(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >), __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > >&&)::{lambda()#1}>(std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<double (*)(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >), __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > >, double>::_Async_state_impl(std::thread::_Invoker<std::tuple<double (*)(__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >), __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > > >&&)::{lambda()#1}&&)':
Client.cpp:(.text._ZNSt6threadC2IZNSt13__future_base17_Async_state_implINS_8_InvokerISt5tupleIJPFdN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEESB_ESB_SB_EEEEdEC4EOSF_EUlvE_JEEEOT_DpOT0_[_ZNSt6threadC5IZNSt13__future_base17_Async_state_implINS_8_InvokerISt5tupleIJPFdN9__gnu_cxx17__normal_iteratorIPdSt6vectorIdSaIdEEEESB_ESB_SB_EEEEdEC4EOSF_EUlvE_JEEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'
На Windows проблем не было.

//(опционально) операционная система
Ubuntu 18.04 Bionic Beaver

**Comment by lpsztemp** [comment]
Надо линковать с библиотекой pthread. Добавь параметр -pthread.
